---
- hosts: webserver
  become: true
  tasks:
  - name: clone the repo with java code on every worker node
    git: repo=https://github.com/Sonal0409/DevOpsCodeDemo.git dest=/home/ansiuser/PROJECT2/code
  - name: Maven to build the code
    command: chdir=/home/ansiuser/PROJECT2/code mvn package
  - name: From target folder copy the addressbook.war in current directory
    copy: src=/home/ansiuser/PROJECT2/code/target/addressbook.war dest=/home/ansiuser/PROJECT2/code remote_src=yes
  - name: Build the dockerfile
    command: chdir=/home/ansiuser/PROJECT2/code  docker build -t myimage:ansible .
  - name: Run the image to deploy the application on tomcat container
    command: docker run -d -P myimage:ansible
